### ISSUE TITLE
Should we clean white spaces in formulas ?

### ISSUE THREAD

**Issue by iOiurson** [anthill/koala#57]
White spaces in formulas are a problem:
- if you clean them up, text variables that include white spaces are perverted
- if you don't, `clean_volatiles()` function might end up not replacing parts of formula since `revert_rpn()` (which outputs the part of the formula to replace) returns a formula without white spaces.

The current set up is not replacing white spaces.

**Comment by bleucitron** [comment]
One solution could be to replace only `', '` by `','`.
