### ISSUE TITLE
Manage Spreadsheet.set_value() on sparse Ranges

### ISSUE THREAD

**Issue by iOiurson** [anthill/koala#72]
Ranges with empty cells end up being sparse Ranges (meaning they lack some Cell references).
Then using `Spreadsheet.set_value()` might result in setting incorrect values on Cells.

**Comment by danielsjf** [comment]
I cannot reproduce this after the last modifications to the ranges. Let's reopen it if there is a reproducible example in the future.

@brianmay, I apparently don't have the permissions to close it.
