### ISSUE TITLE
False circular references

### ISSUE THREAD

**Issue by iOiurson** [anthill/koala#8]
Formulas like:
`=(totalDecom-SUM(INDEX(FA_RecCostsDecom;1;1):INDEX(FA_RecCostsDecom;1;CA_Periods-1)))*Deprec_UOPRates` when calculated on a cell referenced as `FA_RecCostsDecom` trigger infinite loop.

This is because currently our koala algorithm reevaluates a range each time it sees it in a formula.
A good way to handle this would be to store Ranges (in a koala sense) in a `Spreadsheet.range_dict` object so that when koala encounters a Range it already knows, it can directly use the values without reevaluating the Range (then avoiding the infinite loop).

2 problems though:
- this means the way to initialize Ranges must be adjusted so that a Range is created in the dict on the first element inserted (otherwise the previous formula wouldn't work either)
- this might be a lot of effort for a few cases, since this might not happen that many times

**Comment by SergeBredin** [comment]
Why Koala algorithm reevaluates each time ??

**Comment by iOiurson** [comment]
Imagine the case:
In cell A1 you write `=A1`, koala would compile this into `eval_cell('A1')`, leading to an infinite loop.
Excel prevents this behaviour by displaying a warning, explaing how to treat Circular references.

But in our case, this is not a real circular reference, since we call the previous cell in the current range. Still, koala doesn't how to compile this, and will end up looping infinitely.

**Comment by SergeBredin** [comment]
Sorry, I thought you were speaking about reevaluating each range for each call
